//! Resolves public source descriptions to lossless range readers.
//!
//! The HTTP implementation preserves geotiff.js `RemoteSource` options but
//! enforces the `AsyncFileReader` contract: a `200` full-file response is
//! rejected by default, `206 Content-Range` offsets and lengths are checked,
//! EOF reads are clipped, and multipart range responses retain input order.

use crate::source::httputils::{
    parse_byte_ranges, parse_content_range_strict, parse_content_type,
    parse_unsatisfied_content_range,
};
use async_tiff::error::{AsyncTiffError, AsyncTiffResult};
use async_tiff::reader::AsyncFileReader;
use async_trait::async_trait;
use bytes::Bytes;
use moka::future::Cache;
use object_store::{ObjectStore, ObjectStoreExt};
use reqwest::header::{ACCEPT_ENCODING, CONTENT_RANGE, CONTENT_TYPE, HeaderMap, RANGE};
use reqwest::{Response, StatusCode};
use std::fmt;
use std::ops::Range;
use std::path::PathBuf;
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};
use tokio::io::{AsyncReadExt, AsyncSeekExt};
use tokio::sync::Mutex;

const UNKNOWN_FILE_SIZE: u64 = u64::MAX;

/// Native form of geotiff.js `RemoteSourceOptions` and
/// `BlockedSourceOptions`.
#[derive(Debug, Clone)]
pub struct HttpSourceOptions {
    /// Extra headers added to every request. `Range` is always generated by
    /// the reader and cannot be overridden accidentally.
    pub headers: HeaderMap,
    /// Maximum ranges sent in a multipart request. Zero disables multipart.
    pub max_ranges: usize,
    /// Accept a server that ignores `Range` and returns the full object.
    pub allow_full_file: bool,
    /// Optional aligned read size, equivalent to geotiff.js `blockSize`.
    /// The 64 KiB default matches the public `fromUrl`/`fromUrls` factories.
    pub block_size: Option<u64>,
    /// Number of aligned blocks retained when `block_size` is enabled.
    pub cache_size: usize,
}

impl Default for HttpSourceOptions {
    fn default() -> Self {
        Self {
            headers: HeaderMap::new(),
            max_ranges: 0,
            allow_full_file: false,
            block_size: Some(65_536),
            cache_size: 100,
        }
    }
}

/// Native source variants corresponding to geotiff.js's public factories.
pub enum SourceSpec {
    /// Bytes already resident in memory (`fromArrayBuffer` in geotiff.js).
    Memory(Bytes),
    File(PathBuf),
    Url(url::Url),
    UrlWithOptions {
        url: url::Url,
        options: HttpSourceOptions,
    },
    Object {
        store: Arc<dyn ObjectStore>,
        path: object_store::path::Path,
    },
}

/// Local-file `AsyncFileReader`. **Not** `async_tiff::reader::TokioReader`:
/// that type's `make_range_request` fills a `Vec::with_capacity(n)` (length
/// 0) via `AsyncReadExt::read`, which reads into the buffer's *length*, not
/// its capacity - so it always reads 0 bytes and every call fails with
/// `EndOfFile(n, 0)`. Confirmed by reading `async-tiff` 0.3.0's own source
/// and reproduced with a real temp-file read (see the test below) before
/// concluding it wasn't a misuse on our end. This is exactly the gap the
/// port's translator-function rule exists for: same external trait
/// contract (`AsyncFileReader`), corrected implementation underneath.
#[derive(Debug)]
pub struct LocalFileReader {
    file: Mutex<tokio::fs::File>,
    len: u64,
}

impl LocalFileReader {
    pub fn new(file: tokio::fs::File, len: u64) -> Self {
        LocalFileReader {
            file: Mutex::new(file),
            len,
        }
    }
}

#[async_trait]
impl AsyncFileReader for LocalFileReader {
    async fn get_bytes(&self, range: Range<u64>) -> AsyncTiffResult<Bytes> {
        if range.start >= self.len || range.start >= range.end {
            return Ok(Bytes::new());
        }

        // `AsyncFileReader` is a range source, and callers such as
        // `ReadaheadMetadataCache` deliberately ask for a fixed-size range
        // that may cross EOF. Match ArrayBuffer/File/HTTP range semantics by
        // clipping the request to the actual source length instead of turning
        // an otherwise valid short file into `UnexpectedEof`.
        let end = range.end.min(self.len);
        let mut file = self.file.lock().await;
        file.seek(std::io::SeekFrom::Start(range.start)).await?;
        let len = usize::try_from(end - range.start).map_err(|_| {
            AsyncTiffError::General("file range is too large for this platform".to_string())
        })?;
        let mut buffer = Vec::new();
        buffer.try_reserve_exact(len).map_err(|error| {
            AsyncTiffError::General(format!(
                "could not allocate {len} bytes for local-file range: {error}"
            ))
        })?;
        buffer.resize(len, 0u8);
        file.read_exact(&mut buffer).await?;
        Ok(Bytes::from(buffer))
    }
}

/// Range reader for object stores that clips requests at the known object
/// length. `object_store::ObjectReader` forwards an oversized range and many
/// backends reject it, while TIFF metadata readahead intentionally crosses
/// EOF for small files.
#[derive(Clone, Debug)]
pub struct ObjectRangeReader {
    store: Arc<dyn ObjectStore>,
    path: object_store::path::Path,
    len: u64,
}

impl ObjectRangeReader {
    pub fn new(store: Arc<dyn ObjectStore>, path: object_store::path::Path, len: u64) -> Self {
        Self { store, path, len }
    }

    fn clip(&self, range: Range<u64>) -> Option<Range<u64>> {
        let end = range.end.min(self.len);
        (range.start < end).then_some(range.start..end)
    }
}

#[async_trait]
impl AsyncFileReader for ObjectRangeReader {
    async fn get_bytes(&self, range: Range<u64>) -> AsyncTiffResult<Bytes> {
        let Some(range) = self.clip(range) else {
            return Ok(Bytes::new());
        };
        self.store
            .get_range(&self.path, range)
            .await
            .map_err(Into::into)
    }

    async fn get_byte_ranges(&self, ranges: Vec<Range<u64>>) -> AsyncTiffResult<Vec<Bytes>> {
        let mut output = vec![Bytes::new(); ranges.len()];
        let mut indices = Vec::new();
        let mut clipped = Vec::new();
        for (index, range) in ranges.into_iter().enumerate() {
            if let Some(range) = self.clip(range) {
                indices.push(index);
                clipped.push(range);
            }
        }
        if clipped.is_empty() {
            return Ok(output);
        }
        let values = self.store.get_ranges(&self.path, &clipped).await?;
        if values.len() != indices.len() {
            return Err(AsyncTiffError::General(format!(
                "object store returned {} ranges for {} requests",
                values.len(),
                indices.len()
            )));
        }
        for (index, value) in indices.into_iter().zip(values) {
            output[index] = value;
        }
        Ok(output)
    }
}

/// Correct `RemoteSource` equivalent for native HTTP.
#[derive(Clone)]
pub struct HttpRangeReader {
    client: reqwest::Client,
    url: url::Url,
    options: HttpSourceOptions,
    file_size: Arc<AtomicU64>,
}

impl fmt::Debug for HttpRangeReader {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("HttpRangeReader")
            .field("url", &self.url)
            .field("options", &self.options)
            .field("file_size", &self.file_size())
            .finish_non_exhaustive()
    }
}

impl HttpRangeReader {
    pub fn new(client: reqwest::Client, url: url::Url, options: HttpSourceOptions) -> Self {
        Self {
            client,
            url,
            options,
            file_size: Arc::new(AtomicU64::new(UNKNOWN_FILE_SIZE)),
        }
    }

    /// File size learned from `Content-Range` or an allowed full response.
    pub fn file_size(&self) -> Option<u64> {
        match self.file_size.load(Ordering::Acquire) {
            UNKNOWN_FILE_SIZE => None,
            value => Some(value),
        }
    }

    fn remember_file_size(&self, size: u64) -> AsyncTiffResult<()> {
        let previous = self.file_size.load(Ordering::Acquire);
        if previous != UNKNOWN_FILE_SIZE && previous != size {
            return Err(AsyncTiffError::General(format!(
                "HTTP source size changed during reading: {previous} -> {size}"
            )));
        }
        self.file_size.store(size, Ordering::Release);
        Ok(())
    }

    fn request(&self, range_header: String) -> reqwest::RequestBuilder {
        let mut headers = self.options.headers.clone();
        // Byte positions must refer to the stored representation, not a
        // transparently compressed transfer representation.
        if !headers.contains_key(ACCEPT_ENCODING) {
            headers.insert(
                ACCEPT_ENCODING,
                "identity".parse().expect("static header value"),
            );
        }
        self.client
            .get(self.url.clone())
            .headers(headers)
            .header(RANGE, range_header)
    }

    fn slice_full_response(&self, body: Bytes, range: Range<u64>) -> AsyncTiffResult<Bytes> {
        self.remember_file_size(body.len() as u64)?;
        let start = usize::try_from(range.start)
            .unwrap_or(usize::MAX)
            .min(body.len());
        let end = usize::try_from(range.end)
            .unwrap_or(usize::MAX)
            .min(body.len());
        if start >= end {
            Ok(Bytes::new())
        } else {
            Ok(body.slice(start..end))
        }
    }

    async fn consume_single_partial(
        &self,
        response: Response,
        requested: Range<u64>,
    ) -> AsyncTiffResult<Bytes> {
        let raw_range = response
            .headers()
            .get(CONTENT_RANGE)
            .and_then(|value| value.to_str().ok())
            .ok_or_else(|| {
                AsyncTiffError::General("HTTP 206 response has no Content-Range".to_string())
            })?;
        let parsed = parse_content_range_strict(raw_range).ok_or_else(|| {
            AsyncTiffError::General(format!("Invalid HTTP Content-Range: {raw_range}"))
        })?;
        let start = parsed.start.expect("strict range start");
        let end = parsed.end.expect("strict range end");
        let total = parsed.total.expect("strict range total");
        let response_end = end + 1;
        let is_complete_request = response_end == requested.end;
        let is_clipped_at_eof = response_end == total && requested.end > total;
        if start != requested.start
            || end >= requested.end
            || (!is_complete_request && !is_clipped_at_eof)
        {
            return Err(AsyncTiffError::General(format!(
                "HTTP Content-Range {start}-{end} does not satisfy requested {}-{}",
                requested.start,
                requested.end - 1
            )));
        }
        self.remember_file_size(total)?;
        let body = response.bytes().await?;
        let expected = end - start + 1;
        if body.len() as u64 != expected {
            return Err(AsyncTiffError::EndOfFile(expected, body.len() as u64));
        }
        Ok(body)
    }

    async fn fetch_range(&self, range: Range<u64>) -> AsyncTiffResult<Bytes> {
        if range.start >= range.end {
            return Ok(Bytes::new());
        }
        if self.file_size().is_some_and(|size| range.start >= size) {
            return Ok(Bytes::new());
        }
        let response = self
            .request(format!("bytes={}-{}", range.start, range.end - 1))
            .send()
            .await?;
        let status = response.status();
        if status == StatusCode::PARTIAL_CONTENT {
            return self.consume_single_partial(response, range).await;
        }
        if status == StatusCode::RANGE_NOT_SATISFIABLE {
            let size = parse_unsatisfied_content_range(
                response
                    .headers()
                    .get(CONTENT_RANGE)
                    .and_then(|value| value.to_str().ok()),
            )
            .ok_or_else(|| {
                AsyncTiffError::General("HTTP 416 response has no valid Content-Range".to_string())
            })?;
            self.remember_file_size(size)?;
            if range.start >= size {
                return Ok(Bytes::new());
            }
            return Err(AsyncTiffError::General(format!(
                "server rejected a satisfiable byte range {}-{} for a {size}-byte source",
                range.start,
                range.end - 1
            )));
        }
        if status.is_success() {
            if !self.options.allow_full_file {
                return Err(AsyncTiffError::General(
                    "Server responded with full file while a byte range was requested".to_string(),
                ));
            }
            return self.slice_full_response(response.bytes().await?, range);
        }
        Err(response
            .error_for_status()
            .expect_err("non-success status")
            .into())
    }

    async fn fetch_ranges_individually(
        &self,
        ranges: Vec<Range<u64>>,
    ) -> AsyncTiffResult<Vec<Bytes>> {
        if ranges.len() <= 1 {
            return match ranges.into_iter().next() {
                Some(range) => Ok(vec![self.fetch_range(range).await?]),
                None => Ok(Vec::new()),
            };
        }

        let mut tasks = tokio::task::JoinSet::new();
        let count = ranges.len();
        for (index, range) in ranges.into_iter().enumerate() {
            let reader = self.clone();
            tasks.spawn(async move { (index, reader.fetch_range(range).await) });
        }
        let mut output = vec![Bytes::new(); count];
        while let Some(result) = tasks.join_next().await {
            let (index, value) = result.map_err(|error| {
                AsyncTiffError::General(format!("HTTP range task failed: {error}"))
            })?;
            output[index] = value?;
        }
        Ok(output)
    }

    async fn fetch_ranges_multipart(&self, ranges: Vec<Range<u64>>) -> AsyncTiffResult<Vec<Bytes>> {
        if ranges.iter().any(|range| range.start >= range.end) {
            // Empty ranges have no legal HTTP Range representation.
            return self.fetch_ranges_individually(ranges).await;
        }
        let range_header = format!(
            "bytes={}",
            ranges
                .iter()
                .map(|range| format!("{}-{}", range.start, range.end - 1))
                .collect::<Vec<_>>()
                .join(",")
        );
        let response = self.request(range_header).send().await?;
        let status = response.status();
        if status == StatusCode::PARTIAL_CONTENT {
            let content_type = parse_content_type(
                response
                    .headers()
                    .get(CONTENT_TYPE)
                    .and_then(|value| value.to_str().ok()),
            );
            if content_type.media_type.as_deref() == Some("multipart/byteranges") {
                let boundary = content_type.parameters.get("boundary").ok_or_else(|| {
                    AsyncTiffError::General(
                        "multipart byte-range response has no boundary".to_string(),
                    )
                })?;
                let parts = parse_byte_ranges(response.bytes().await?, boundary)
                    .map_err(AsyncTiffError::General)?;
                let mut output = Vec::with_capacity(ranges.len());
                for requested in &ranges {
                    let part = parts.iter().find(|part| {
                        part.offset == requested.start && part.offset + part.length <= requested.end
                    });
                    match part {
                        Some(part) => {
                            self.remember_file_size(part.file_size)?;
                            output.push(part.data.clone());
                        }
                        None => output.push(self.fetch_range(requested.clone()).await?),
                    }
                }
                return Ok(output);
            }

            // Some servers ignore all ranges after the first. Reuse that
            // response and fetch the remainder separately, as geotiff.js does.
            let mut output = Vec::with_capacity(ranges.len());
            output.push(
                self.consume_single_partial(response, ranges[0].clone())
                    .await?,
            );
            output.extend(self.fetch_ranges_individually(ranges[1..].to_vec()).await?);
            return Ok(output);
        }
        if status == StatusCode::RANGE_NOT_SATISFIABLE {
            return self.fetch_ranges_individually(ranges).await;
        }
        if status.is_success() {
            if !self.options.allow_full_file {
                return Err(AsyncTiffError::General(
                    "Server responded with full file while byte ranges were requested".to_string(),
                ));
            }
            let body = response.bytes().await?;
            self.remember_file_size(body.len() as u64)?;
            return ranges
                .into_iter()
                .map(|range| self.slice_full_response(body.clone(), range))
                .collect();
        }
        Err(response
            .error_for_status()
            .expect_err("non-success status")
            .into())
    }
}

#[async_trait]
impl AsyncFileReader for HttpRangeReader {
    async fn get_bytes(&self, range: Range<u64>) -> AsyncTiffResult<Bytes> {
        self.fetch_range(range).await
    }

    async fn get_byte_ranges(&self, ranges: Vec<Range<u64>>) -> AsyncTiffResult<Vec<Bytes>> {
        if self.options.max_ranges > 0
            && ranges.len() > 1
            && ranges.len() <= self.options.max_ranges
        {
            self.fetch_ranges_multipart(ranges).await
        } else {
            self.fetch_ranges_individually(ranges).await
        }
    }
}

/// Aligned block cache corresponding to geotiff.js `BlockedSource`.
/// Concurrent misses for the same block are coalesced by moka.
#[derive(Clone)]
pub struct BlockedReader {
    inner: Arc<dyn AsyncFileReader>,
    block_size: u64,
    cache: Cache<u64, Bytes>,
}

impl fmt::Debug for BlockedReader {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("BlockedReader")
            .field("block_size", &self.block_size)
            .field("cached_blocks", &self.cache.entry_count())
            .finish_non_exhaustive()
    }
}

impl BlockedReader {
    pub fn new(
        inner: Arc<dyn AsyncFileReader>,
        block_size: u64,
        cache_size: usize,
    ) -> AsyncTiffResult<Self> {
        if block_size == 0 {
            return Err(AsyncTiffError::General(
                "HTTP block_size must be greater than zero".to_string(),
            ));
        }
        if cache_size == 0 {
            return Err(AsyncTiffError::General(
                "HTTP cache_size must be greater than zero".to_string(),
            ));
        }
        Ok(Self {
            inner,
            block_size,
            cache: Cache::builder().max_capacity(cache_size as u64).build(),
        })
    }

    async fn block(&self, block_id: u64) -> AsyncTiffResult<Bytes> {
        let start = block_id
            .checked_mul(self.block_size)
            .ok_or_else(|| AsyncTiffError::General("HTTP block offset overflow".to_string()))?;
        let end = start
            .checked_add(self.block_size)
            .ok_or_else(|| AsyncTiffError::General("HTTP block range overflow".to_string()))?;
        let inner = self.inner.clone();
        self.cache
            .try_get_with(block_id, async move { inner.get_bytes(start..end).await })
            .await
            .map_err(|error| AsyncTiffError::General(error.to_string()))
    }
}

#[async_trait]
impl AsyncFileReader for BlockedReader {
    async fn get_bytes(&self, range: Range<u64>) -> AsyncTiffResult<Bytes> {
        if range.start >= range.end {
            return Ok(Bytes::new());
        }
        let last_byte = range.end - 1;
        let first_block = range.start / self.block_size;
        let last_block = last_byte / self.block_size;
        let requested_len = range.end - range.start;
        let requested_len = usize::try_from(requested_len).map_err(|_| {
            AsyncTiffError::General("HTTP block request is too large for this platform".to_string())
        })?;
        let mut output = Vec::new();
        output.try_reserve_exact(requested_len).map_err(|error| {
            AsyncTiffError::General(format!(
                "could not allocate {requested_len} bytes for HTTP blocks: {error}"
            ))
        })?;

        for block_id in first_block..=last_block {
            let block = self.block(block_id).await?;
            let block_offset = block_id
                .checked_mul(self.block_size)
                .ok_or_else(|| AsyncTiffError::General("HTTP block offset overflow".to_string()))?;
            let block_end = block_offset.saturating_add(block.len() as u64);
            let copy_start = range.start.max(block_offset);
            let copy_end = range.end.min(block_end);
            if copy_start < copy_end {
                let local_start = usize::try_from(copy_start - block_offset).map_err(|_| {
                    AsyncTiffError::General("HTTP block index is too large".to_string())
                })?;
                let local_end = usize::try_from(copy_end - block_offset).map_err(|_| {
                    AsyncTiffError::General("HTTP block index is too large".to_string())
                })?;
                output.extend_from_slice(&block[local_start..local_end]);
            }
            if block.len() as u64 != self.block_size {
                // A conforming short block is the final block of the file.
                break;
            }
        }
        Ok(Bytes::from(output))
    }
}

fn configured_http_reader(
    client: reqwest::Client,
    url: url::Url,
    options: HttpSourceOptions,
) -> AsyncTiffResult<Arc<dyn AsyncFileReader>> {
    let block_options = options.block_size.map(|size| (size, options.cache_size));
    let reader: Arc<dyn AsyncFileReader> = Arc::new(HttpRangeReader::new(client, url, options));
    match block_options {
        Some((block_size, cache_size)) => Ok(Arc::new(BlockedReader::new(
            reader, block_size, cache_size,
        )?)),
        None => Ok(reader),
    }
}

/// In-memory range reader used by the public `from_bytes`/`fromArrayBuffer`
/// equivalent. Slices are clipped at EOF exactly like `ArrayBuffer.slice`.
#[derive(Debug, Clone)]
pub struct MemoryReader(Bytes);

impl MemoryReader {
    pub fn new(bytes: Bytes) -> Self {
        Self(bytes)
    }
}

#[async_trait]
impl AsyncFileReader for MemoryReader {
    async fn get_bytes(&self, range: Range<u64>) -> AsyncTiffResult<Bytes> {
        let start = usize::try_from(range.start)
            .unwrap_or(usize::MAX)
            .min(self.0.len());
        let end = usize::try_from(range.end)
            .unwrap_or(usize::MAX)
            .min(self.0.len());
        if start >= end {
            return Ok(Bytes::new());
        }
        Ok(self.0.slice(start..end))
    }
}

/// Resolves a source into the common range-reader contract.
pub async fn open_reader(
    spec: SourceSpec,
    http_client: reqwest::Client,
) -> AsyncTiffResult<Arc<dyn AsyncFileReader>> {
    match spec {
        SourceSpec::Memory(bytes) => {
            Ok(Arc::new(MemoryReader::new(bytes)) as Arc<dyn AsyncFileReader>)
        }
        SourceSpec::File(path) => {
            let file = tokio::fs::File::open(path).await?;
            let len = file.metadata().await?.len();
            Ok(Arc::new(LocalFileReader::new(file, len)) as Arc<dyn AsyncFileReader>)
        }
        SourceSpec::Url(url) => {
            configured_http_reader(http_client, url, HttpSourceOptions::default())
        }
        SourceSpec::UrlWithOptions { url, options } => {
            configured_http_reader(http_client, url, options)
        }
        SourceSpec::Object { store, path } => {
            let len = store.head(&path).await?.size;
            Ok(Arc::new(ObjectRangeReader::new(store, path, len)) as Arc<dyn AsyncFileReader>)
        }
    }
}

impl fmt::Debug for SourceSpec {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SourceSpec::Memory(bytes) => write!(f, "SourceSpec::Memory({} bytes)", bytes.len()),
            SourceSpec::File(p) => write!(f, "SourceSpec::File({p:?})"),
            SourceSpec::Url(u) => write!(f, "SourceSpec::Url({u})"),
            SourceSpec::UrlWithOptions { url, options } => f
                .debug_struct("SourceSpec::UrlWithOptions")
                .field("url", url)
                .field("options", options)
                .finish(),
            SourceSpec::Object { path, .. } => write!(f, "SourceSpec::Object({path})"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::{Read, Write};
    use std::net::TcpListener;
    use std::thread;

    fn serve_once(response: Vec<u8>) -> (url::Url, thread::JoinHandle<String>) {
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let address = listener.local_addr().unwrap();
        let handle = thread::spawn(move || {
            let (mut stream, _) = listener.accept().unwrap();
            stream
                .set_read_timeout(Some(std::time::Duration::from_secs(5)))
                .unwrap();
            let mut request = Vec::new();
            let mut chunk = [0u8; 1024];
            while !request.windows(4).any(|window| window == b"\r\n\r\n") {
                let read = stream.read(&mut chunk).unwrap();
                if read == 0 {
                    break;
                }
                request.extend_from_slice(&chunk[..read]);
            }
            stream.write_all(&response).unwrap();
            String::from_utf8(request).unwrap()
        });
        (
            url::Url::parse(&format!("http://{address}/data.tif")).unwrap(),
            handle,
        )
    }

    fn http_response(status: &str, headers: &[(&str, &str)], body: &[u8]) -> Vec<u8> {
        let mut response = format!(
            "HTTP/1.1 {status}\r\nContent-Length: {}\r\nConnection: close\r\n",
            body.len()
        );
        for (name, value) in headers {
            response.push_str(name);
            response.push_str(": ");
            response.push_str(value);
            response.push_str("\r\n");
        }
        response.push_str("\r\n");
        let mut bytes = response.into_bytes();
        bytes.extend_from_slice(body);
        bytes
    }

    #[tokio::test]
    async fn opens_a_local_file_and_reads_an_exact_range() {
        let mut path = std::env::temp_dir();
        path.push(format!("geotiff-rs-reader-test-{}.bin", std::process::id()));
        tokio::fs::write(&path, b"GEOTIFF-TEST-BYTES")
            .await
            .unwrap();

        let reader = open_reader(SourceSpec::File(path.clone()), reqwest::Client::new())
            .await
            .unwrap();
        let bytes = reader.get_bytes(0..18).await.unwrap();
        assert_eq!(&bytes[..], b"GEOTIFF-TEST-BYTES");

        tokio::fs::remove_file(&path).await.ok();
    }

    #[tokio::test]
    async fn reads_a_sub_range_not_starting_at_zero() {
        let mut path = std::env::temp_dir();
        path.push(format!(
            "geotiff-rs-reader-test-subrange-{}.bin",
            std::process::id()
        ));
        tokio::fs::write(&path, b"0123456789").await.unwrap();

        let reader = open_reader(SourceSpec::File(path.clone()), reqwest::Client::new())
            .await
            .unwrap();
        let bytes = reader.get_bytes(3..7).await.unwrap();
        assert_eq!(&bytes[..], b"3456");

        tokio::fs::remove_file(&path).await.ok();
    }

    #[tokio::test]
    async fn missing_local_file_surfaces_an_io_error() {
        let mut path = std::env::temp_dir();
        path.push(format!(
            "geotiff-rs-reader-test-missing-{}.bin",
            std::process::id()
        ));
        let result = open_reader(SourceSpec::File(path), reqwest::Client::new()).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn range_past_end_of_file_is_clipped() {
        let mut path = std::env::temp_dir();
        path.push(format!(
            "geotiff-rs-reader-test-short-{}.bin",
            std::process::id()
        ));
        tokio::fs::write(&path, b"short").await.unwrap();

        let reader = open_reader(SourceSpec::File(path.clone()), reqwest::Client::new())
            .await
            .unwrap();
        let result = reader.get_bytes(0..100).await.unwrap();
        assert_eq!(&result[..], b"short");

        let empty = reader.get_bytes(100..200).await.unwrap();
        assert!(empty.is_empty());

        tokio::fs::remove_file(&path).await.ok();
    }

    #[tokio::test]
    async fn memory_source_matches_array_buffer_slice_semantics() {
        let reader = open_reader(
            SourceSpec::Memory(Bytes::from_static(b"0123456789")),
            reqwest::Client::new(),
        )
        .await
        .unwrap();
        assert_eq!(&reader.get_bytes(3..7).await.unwrap()[..], b"3456");
        assert_eq!(&reader.get_bytes(8..100).await.unwrap()[..], b"89");
        assert!(reader.get_bytes(100..200).await.unwrap().is_empty());
    }

    #[tokio::test]
    async fn http_reader_validates_ranges_and_sends_custom_headers() {
        let response = http_response(
            "206 Partial Content",
            &[("Content-Range", "bytes 3-6/10")],
            b"3456",
        );
        let (url, server) = serve_once(response);
        let mut options = HttpSourceOptions::default();
        options.headers.insert("x-test", "present".parse().unwrap());
        let reader = HttpRangeReader::new(reqwest::Client::new(), url, options);
        assert_eq!(reader.get_bytes(3..7).await.unwrap().as_ref(), b"3456");
        assert_eq!(reader.file_size(), Some(10));

        let request = server.join().unwrap().to_ascii_lowercase();
        assert!(request.contains("range: bytes=3-6\r\n"));
        assert!(request.contains("x-test: present\r\n"));
        assert!(request.contains("accept-encoding: identity\r\n"));
    }

    #[tokio::test]
    async fn http_reader_rejects_full_file_by_default() {
        let (url, server) = serve_once(http_response("200 OK", &[], b"0123456789"));
        let reader =
            HttpRangeReader::new(reqwest::Client::new(), url, HttpSourceOptions::default());
        let error = reader.get_bytes(3..7).await.unwrap_err();
        assert!(error.to_string().contains("full file"));
        server.join().unwrap();
    }

    #[tokio::test]
    async fn http_reader_can_explicitly_slice_a_full_file_response() {
        let (url, server) = serve_once(http_response("200 OK", &[], b"0123456789"));
        let options = HttpSourceOptions {
            allow_full_file: true,
            ..HttpSourceOptions::default()
        };
        let reader = HttpRangeReader::new(reqwest::Client::new(), url, options);
        assert_eq!(reader.get_bytes(3..7).await.unwrap().as_ref(), b"3456");
        assert_eq!(reader.file_size(), Some(10));
        server.join().unwrap();
    }

    #[tokio::test]
    async fn http_reader_rejects_a_shifted_content_range() {
        let response = http_response(
            "206 Partial Content",
            &[("Content-Range", "bytes 2-5/10")],
            b"2345",
        );
        let (url, server) = serve_once(response);
        let reader =
            HttpRangeReader::new(reqwest::Client::new(), url, HttpSourceOptions::default());
        assert!(reader.get_bytes(3..7).await.is_err());
        server.join().unwrap();
    }

    #[tokio::test]
    async fn http_reader_accepts_a_short_final_range_and_clips_future_reads() {
        let response = http_response(
            "206 Partial Content",
            &[("Content-Range", "bytes 8-9/10")],
            b"89",
        );
        let (url, server) = serve_once(response);
        let reader =
            HttpRangeReader::new(reqwest::Client::new(), url, HttpSourceOptions::default());
        assert_eq!(reader.get_bytes(8..100).await.unwrap().as_ref(), b"89");
        server.join().unwrap();
        // No second HTTP request is made after the size is known.
        assert!(reader.get_bytes(10..100).await.unwrap().is_empty());
    }

    #[tokio::test]
    async fn http_reader_rejects_a_short_non_final_partial_response() {
        let response = http_response(
            "206 Partial Content",
            &[("Content-Range", "bytes 3-5/10")],
            b"345",
        );
        let (url, server) = serve_once(response);
        let reader =
            HttpRangeReader::new(reqwest::Client::new(), url, HttpSourceOptions::default());
        let error = reader.get_bytes(3..7).await.unwrap_err();
        assert!(error.to_string().contains("does not satisfy requested"));
        server.join().unwrap();
    }

    #[tokio::test]
    async fn http_reader_parses_multipart_ranges_in_request_order() {
        let body = b"--xyz\r\nContent-Range: bytes 8-9/10\r\n\r\n89\r\n--xyz\r\nContent-Range: bytes 2-4/10\r\n\r\n234\r\n--xyz--\r\n";
        let response = http_response(
            "206 Partial Content",
            &[("Content-Type", "multipart/byteranges; boundary=\"xyz\"")],
            body,
        );
        let (url, server) = serve_once(response);
        let options = HttpSourceOptions {
            max_ranges: 2,
            ..HttpSourceOptions::default()
        };
        let reader = HttpRangeReader::new(reqwest::Client::new(), url, options);
        let values = reader.get_byte_ranges(vec![2..5, 8..10]).await.unwrap();
        assert_eq!(values[0].as_ref(), b"234");
        assert_eq!(values[1].as_ref(), b"89");
        let request = server.join().unwrap().to_ascii_lowercase();
        assert!(request.contains("range: bytes=2-4,8-9\r\n"));
    }

    #[derive(Debug)]
    struct RecordingReader {
        data: Bytes,
        ranges: Arc<std::sync::Mutex<Vec<Range<u64>>>>,
    }

    #[async_trait]
    impl AsyncFileReader for RecordingReader {
        async fn get_bytes(&self, range: Range<u64>) -> AsyncTiffResult<Bytes> {
            self.ranges.lock().unwrap().push(range.clone());
            let start = usize::try_from(range.start)
                .unwrap_or(usize::MAX)
                .min(self.data.len());
            let end = usize::try_from(range.end)
                .unwrap_or(usize::MAX)
                .min(self.data.len());
            Ok(if start < end {
                self.data.slice(start..end)
            } else {
                Bytes::new()
            })
        }
    }

    #[tokio::test]
    async fn blocked_reader_aligns_and_reuses_blocks() {
        let ranges = Arc::new(std::sync::Mutex::new(Vec::new()));
        let inner: Arc<dyn AsyncFileReader> = Arc::new(RecordingReader {
            data: Bytes::from_static(b"0123456789"),
            ranges: ranges.clone(),
        });
        let reader = BlockedReader::new(inner, 4, 10).unwrap();
        assert_eq!(reader.get_bytes(3..7).await.unwrap().as_ref(), b"3456");
        assert_eq!(reader.get_bytes(4..6).await.unwrap().as_ref(), b"45");
        assert_eq!(&*ranges.lock().unwrap(), &[0..4, 4..8]);
    }

    #[tokio::test]
    async fn object_reader_clips_metadata_readahead_at_eof() {
        let store = Arc::new(object_store::memory::InMemory::new());
        let path = object_store::path::Path::from("small.tif");
        store
            .put(&path, Bytes::from_static(b"0123456789").into())
            .await
            .unwrap();
        let reader = open_reader(SourceSpec::Object { store, path }, reqwest::Client::new())
            .await
            .unwrap();
        assert_eq!(reader.get_bytes(8..65_536).await.unwrap().as_ref(), b"89");
        assert!(reader.get_bytes(10..20).await.unwrap().is_empty());
    }
}
